/**
 * SpecVectorIndex
 *
 * Builds and queries a LanceDB vector index over OpenSpec spec files.
 * Each record represents a logical section (requirement, purpose, design note...)
 * parsed from the Markdown spec files.
 *
 * Storage: <outputDir>/vector-index/  (same LanceDB folder as VectorIndex, different table)
 * Table name: "specs"
 *
 * Usage:
 *   // Build (or rebuild)
 *   await SpecVectorIndex.build(outputDir, specsDir, mappingJson, embedSvc);
 *
 *   // Search
 *   const results = await SpecVectorIndex.search(outputDir, "email validation", embedSvc);
 */

import { existsSync } from 'node:fs';
import { openVectorBackend, type VectorRecord } from './vector-store.js';
import { readdir, readFile } from 'node:fs/promises';
import { join, basename, dirname } from 'node:path';
import { fileExists } from '../../utils/command-helpers.js';
import type { EmbeddingService } from './embedding-service.js';

// ============================================================================
// TYPES
// ============================================================================

export interface SpecRecord {
  id: string;           // "analyzer.map"
  domain: string;       // "analyzer"
  section: string;      // "requirements" | "purpose" | "entities" | "design" | "architecture" | "other"
  title: string;        // "Requirement: Map" or "Purpose"
  /** Concatenated text used for embedding */
  text: string;
  /** Source files linked to this requirement (from mapping.json) */
  linkedFiles: string;  // JSON-encoded string[] (LanceDB stores as string)
  /** Embedding vector */
  vector: number[];
}

export interface SpecSearchResult {
  record: {
    id: string;
    domain: string;
    section: string;
    title: string;
    text: string;
    /** Parsed from JSON -- list of source file paths linked to this spec section */
    linkedFiles: string[];
  };
  score: number;
}

// ============================================================================
// CONSTANTS
// ============================================================================

const DB_FOLDER = 'vector-index';
const TABLE_NAME = 'specs';

// Mapping entry shape from .openlore/analysis/mapping.json
interface MappingEntry {
  requirement: string;
  service?: string;
  domain: string;
  specFile?: string;
  functions?: Array<{ name: string; file: string; line?: number; kind?: string; confidence?: string }>;
}

// ============================================================================
// MARKDOWN PARSER
// ============================================================================

interface ParsedSection {
  section: string;
  title: string;
  content: string;
  requirementKey?: string; // slugified requirement name for mapping lookup
}

/**
 * Parse a spec Markdown file into logical sections.
 * Each H2 becomes a section; H3 within Requirements becomes individual items.
 */
function parseSpecFile(markdown: string): ParsedSection[] {
  const lines = markdown.split('\n');
  const results: ParsedSection[] = [];

  let currentH2 = '';
  let currentH2Section = '';
  let currentH3 = '';
  let currentH3Key = '';
  let buffer: string[] = [];

  const flush = () => {
    const content = buffer.join('\n').trim();
    if (!content) return;

    if (currentH3 && currentH2Section === 'requirements') {
      results.push({
        section: 'requirements',
        title: currentH3,
        content,
        requirementKey: currentH3Key,
      });
    } else if (currentH2) {
      results.push({
        section: currentH2Section,
        title: currentH2,
        content,
      });
    }
    buffer = [];
  };

  for (const line of lines) {
    // Skip generator comment lines
    if (line.startsWith('> Generated by')) continue;
    if (line.startsWith('> Source files:')) continue;

    const h2Match = line.match(/^## (.+)/);
    const h3Match = line.match(/^### (.+)/);

    if (h2Match) {
      flush();
      currentH2 = h2Match[1].trim();
      currentH2Section = slugifySection(currentH2);
      currentH3 = '';
      currentH3Key = '';
    } else if (h3Match && currentH2Section === 'requirements') {
      flush();
      currentH3 = h3Match[1].trim();
      currentH3Key = slugifyRequirement(currentH3);
    } else if (!line.startsWith('# ')) {
      // Skip H1 (spec title handled by filename/domain)
      buffer.push(line);
    }
  }
  flush();

  return results;
}

function slugifySection(title: string): string {
  const lower = title.toLowerCase();
  if (lower.includes('purpose')) return 'purpose';
  if (lower.includes('entit')) return 'entities';
  if (lower.includes('requirement')) return 'requirements';
  if (lower.includes('design')) return 'design';
  if (lower.includes('architecture')) return 'architecture';
  if (lower.includes('sub-component') || lower.includes('subcomponent')) return 'subcomponents';
  return lower.replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

/** Extract requirement key from "Requirement: MapSomething" -> "mapSomething" */
function slugifyRequirement(title: string): string {
  const withoutPrefix = title.replace(/^Requirement:\s*/i, '').trim();
  // camelCase -> first char lowercase
  return withoutPrefix.charAt(0).toLowerCase() + withoutPrefix.slice(1);
}

// ============================================================================
// MAPPING INDEX
// ============================================================================

/**
 * Build a lookup: "domain:requirementKey" -> string[] of source files.
 * Filters out wildcard entries (*) and deduplicates.
 */
function buildMappingIndex(mappings: MappingEntry[]): Map<string, string[]> {
  const index = new Map<string, string[]>();
  for (const m of mappings) {
    const key = `${m.domain}:${m.requirement}`;
    const files = (m.functions ?? [])
      .map(f => f.file)
      .filter(f => f && f !== '*');
    if (files.length > 0) {
      const existing = index.get(key) ?? [];
      const merged = [...new Set([...existing, ...files])];
      index.set(key, merged);
    }
  }
  return index;
}

// ============================================================================
// TEXT BUILDER
// ============================================================================

function buildText(domain: string, section: ParsedSection): string {
  const parts = [`[spec:${domain}] ${section.title}`];
  if (section.content) parts.push(section.content);
  return parts.join('\n');
}

// ============================================================================
// ADR PARSER
// ============================================================================

interface AdrRecord {
  id: string;
  domain: string;
  section: string;
  title: string;
  text: string;
  linkedFiles: string;
}

async function findAdrFiles(decisionsDir: string): Promise<string[]> {
  if (!(await fileExists(decisionsDir))) return [];
  try {
    const entries = await readdir(decisionsDir);
    return entries
      .filter((f) => /^adr-\d+.*\.md$/i.test(f))
      .map((f) => join(decisionsDir, f));
  } catch {
    return [];
  }
}

async function parseAdrFiles(decisionsDir: string): Promise<AdrRecord[]> {
  const files = await findAdrFiles(decisionsDir);
  const records: AdrRecord[] = [];

  for (const filePath of files) {
    try {
      const content = await readFile(filePath, 'utf-8');
      const titleMatch = content.match(/^#\s+(ADR-\d+):\s+(.+)$/m);
      if (!titleMatch) continue;
      const adrNum = titleMatch[1];
      const title = titleMatch[2].trim();

      records.push({
        id: `decisions.${adrNum.toLowerCase()}`,
        domain: 'decisions',
        section: adrNum,
        title: `${adrNum}: ${title}`,
        text: `[decision] ${adrNum}: ${title}\n${content}`,
        linkedFiles: '[]',
      });
    } catch {
      continue;
    }
  }

  return records;
}

// ============================================================================
// SPEC VECTOR INDEX
// ============================================================================

export class SpecVectorIndex {
  /**
   * Discover all spec.md files under specsDir, parse them, enrich with mapping,
   * embed, and write to LanceDB table "specs".
   *
   * @param outputDir  Path to .openlore/analysis/
   * @param specsDir   Path to openspec/specs/ (or any directory containing domain/spec.md files)
   * @param mappingJsonPath  Path to mapping.json (optional -- no enrichment if absent)
   */
  static async build(
    outputDir: string,
    specsDir: string,
    embedSvc: EmbeddingService,
    mappingJsonPath?: string,
    decisionsDir?: string
  ): Promise<{ recordCount: number }> {
    // Load mapping index (optional)
    let mappingIndex = new Map<string, string[]>();
    if (mappingJsonPath && await fileExists(mappingJsonPath)) {
      try {
        const raw = JSON.parse(await readFile(mappingJsonPath, 'utf-8'));
        mappingIndex = buildMappingIndex((raw.mappings ?? []) as MappingEntry[]);
      } catch {
        // non-fatal -- proceed without enrichment
      }
    }

    // Discover spec files
    const specFiles = await findSpecFiles(specsDir);
    if (specFiles.length === 0) {
      throw new Error(`No spec.md files found in ${specsDir}`);
    }

    // Parse all specs into records (without vectors)
    const records: Omit<SpecRecord, 'vector'>[] = [];

    for (const specFile of specFiles) {
      const domain = basename(dirname(specFile));
      let markdown: string;
      try {
        markdown = await readFile(specFile, 'utf-8');
      } catch {
        continue;
      }

      const sections = parseSpecFile(markdown);

      for (const sec of sections) {
        const reqKey = sec.requirementKey ?? sec.section;
        const mappingKey = `${domain}:${reqKey}`;
        const linkedFiles = mappingIndex.get(mappingKey) ?? [];

        const id = sec.requirementKey
          ? `${domain}.${sec.requirementKey}`
          : `${domain}.${sec.section}`;

        const text = buildText(domain, sec);

        records.push({
          id,
          domain,
          section: sec.section,
          title: sec.title,
          text,
          linkedFiles: JSON.stringify(linkedFiles),
        });
      }
    }

    // Also index ADR files from openspec/decisions/ if decisionsDir provided
    if (decisionsDir) {
      const adrRecords = await parseAdrFiles(decisionsDir);
      records.push(...adrRecords);
    }

    if (records.length === 0) {
      throw new Error('No spec sections could be parsed');
    }

    // Batch-embed
    const texts = records.map(r => r.text);
    const vectors = await embedSvc.embed(texts);

    if (vectors.length !== records.length) {
      throw new Error(`Embedding count mismatch: expected ${records.length}, got ${vectors.length}`);
    }

    const fullRecords: SpecRecord[] = records.map((r, i) => ({
      ...r,
      vector: vectors[i],
    }));

    // Write store (same DB folder, table "specs") — LanceDB | Qdrant (по QDRANT_URL)
    const dbPath = join(outputDir, DB_FOLDER);
    await openVectorBackend(dbPath, TABLE_NAME).build(fullRecords as unknown as VectorRecord[]);

    return { recordCount: fullRecords.length };
  }

  /**
   * Semantic search over the spec index.
   */
  static async search(
    outputDir: string,
    query: string,
    embedSvc: EmbeddingService,
    opts: {
      limit?: number;
      domain?: string;
      section?: string;
    } = {}
  ): Promise<SpecSearchResult[]> {
    const { limit = 10, domain, section } = opts;

    if (!SpecVectorIndex.exists(outputDir)) {
      throw new Error('No spec index found. Run "openlore analyze --embed" or "openlore analyze --reindex-specs" first.');
    }

    const [queryVector] = await embedSvc.embed([query]);
    if (!queryVector) throw new Error('Failed to embed query');

    const dbPath = join(outputDir, DB_FOLDER);
    const backend = openVectorBackend(dbPath, TABLE_NAME);   // LanceDB | Qdrant (по QDRANT_URL)

    const fetchLimit = Math.min(limit * 10, 500);
    const rows = await backend.searchDense(queryVector, fetchLimit);

    const filtered = rows
      .filter(row => {
        if (domain && (row.domain as string) !== domain) return false;
        if (section && (row.section as string) !== section) return false;
        return true;
      })
      .slice(0, limit);

    return filtered.map(row => {
      let linkedFiles: string[] = [];
      try {
        linkedFiles = JSON.parse(row.linkedFiles as string) as string[];
      } catch { /* ignore */ }

      return {
        record: {
          id: row.id as string,
          domain: row.domain as string,
          section: row.section as string,
          title: row.title as string,
          text: row.text as string,
          linkedFiles,
        },
        score: row._distance as number,
      };
    });
  }

  /**
   * Returns true if the spec index table exists.
   */
  static exists(outputDir: string): boolean {
    // LanceDB: <db>/specs.lance · Qdrant: маркер <db>/.qdrant-specs (backend.exists, table-specific)
    return openVectorBackend(join(outputDir, DB_FOLDER), TABLE_NAME).exists();
  }
}

// ============================================================================
// HELPERS
// ============================================================================

async function findSpecFiles(specsDir: string): Promise<string[]> {
  if (!await fileExists(specsDir)) return [];
  const results: string[] = [];

  let entries: string[];
  try {
    entries = await readdir(specsDir);
  } catch {
    return [];
  }

  for (const entry of entries) {
    const domainDir = join(specsDir, entry);
    const specFile = join(domainDir, 'spec.md');
    if (await fileExists(specFile)) {
      results.push(specFile);
    }
  }

  return results;
}
